// ============================================================
// posts.js — Portfolio data layer
// ============================================================
// This file is the ONLY source of post data in the portfolio.
// It fetches the api/posts.json file (automatically generated
// by the posts_carlos repository via GitHub Actions) and exposes
// two functions for the rest of the application to use:
//
//   getPosts()       → returns all posts
//   getPost(slug)    → returns a specific post by its slug
//
// You NEVER need to edit this file to add posts.
// Just push to posts_carlos and the JSON updates itself.
// ============================================================

// Path to the JSON generated by the posts_carlos pipeline.
// GitHub Actions copies dist/posts.json to api/posts.json
// in this repository on each push to the posts_carlos main branch.
const POSTS_JSON_URL = './api/posts.json';

// Internal cache — prevents fetching multiple times in the same session.
// On the first call it fetches and stores. Subsequent calls reuse it.
let _cache = null;

// ── fetchPosts ──────────────────────────────────────────────
// Internal function. Fetches the JSON once and stores it in cache.
// Always returns an array (empty on error to avoid breaking the UI).
async function fetchPosts() {
  if (_cache) return _cache; // already fetched, return from cache

  try {
    const response = await fetch(POSTS_JSON_URL);

    // If the server returned an error (404, 500, etc.), throw.
    if (!response.ok) {
      throw new Error(`Error fetching posts: ${response.status} ${response.statusText}`);
    }

    const posts = await response.json();
    _cache = posts; // save to cache
    return posts;

  } catch (err) {
    // If fetch fails (no internet, file missing, etc.),
    // log the error and return empty array so UI doesn't break
    console.error('[posts.js] Unable to load posts:', err);
    return [];
  }
}

// ── getPosts ────────────────────────────────────────────────
// Returns all posts, already sorted by date (newest first).
// The JSON is pre-sorted by generate-json.js, but we sort
// again here as a safety measure.
//
// Usage in script.js:
//   const posts = await getPosts();
export async function getPosts() {
  const posts = await fetchPosts();

  return posts.sort((a, b) => {
    // Compare dates as ISO strings (YYYY-MM-DD) — works out of the box
    return a.date < b.date ? 1 : -1;
  });
}

// ── getPost ─────────────────────────────────────────────────
// Returns a single post by slug, or null if not found.
// The slug is the unique identifier for each post (e.g. "arquitetura-limpa").
//
// Usage in script.js:
//   const post = await getPost('arquitetura-limpa');
export async function getPost(slug) {
  const posts = await fetchPosts();

  // Find the post whose slug matches the given parameter
  const post = posts.find(p => p.slug === slug);

  if (!post) {
    console.warn(`[posts.js] Post not found: "${slug}"`);
    return null;
  }

  return post;
}

// ── getPostsByTag ────────────────────────────────────────────
// Bonus: returns all posts that have a given tag.
// Useful if you want to add tag filtering in the future.
//
// Usage:
//   const posts = await getPostsByTag('javascript');
export async function getPostsByTag(tag) {
  const posts = await fetchPosts();
  return posts.filter(p => p.tags && p.tags.includes(tag));
}